kind: pipeline
# you could have [type: kubernetes]
type: docker
name: default

steps:
- name: testpipeline1
  image: alpine
  commands:
  - echo 'This'
  - echo 'is'
  - echo 'Gravitee Gateway!'
- name: testpipeline2
  image: alpine
  commands:
  - echo "We are in [$(pwd)]"
  - ls -allh
  - echo 'ok!'
- name: mavenbuild
  # image: adoptopenjdk/openjdk11:jre-11.0.7_10-alpine
  image: maven:3-jdk-10
  commands:
    - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
    # - mvn package
- name: graviteebuild
  image: maven:3-jdk-10
  commands:
    - mvn clean compile exec:java -Pdev -pl gravitee-gateway-standalone/gravitee-gateway-standalone-container
