kind: pipeline
# you could have [type: kubernetes]
type: docker
name: default

steps:
- name: testpipeline1
  image: alpine
  commands:
  - echo 'This'
  - echo 'is'
  - echo 'Gravitee Gateway!'
- name: testpipeline2
  image: alpine
  commands:
  - echo "We are in [$(pwd)]"
  - ls -allh
  - echo 'ok!'

# A standard java maven build
- name: mavenstdbuild
  # image: adoptopenjdk/openjdk11:jre-11.0.7_10-alpine
  image: maven:3-jdk-11
  commands:
    - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
    - mvn package

# ---
# The java maven build defined by the appveyor.yml file :
# https://github.com/gravitee-lab/gravitee-gateway/blob/master/appveyor.yml
# ---
- name: build_appveyor
  # image: adoptopenjdk/openjdk11:jre-11.0.7_10-alpine
  image: maven:3-jdk-11
  commands:
  - mvn clean package --batch-mode -DskipTest
- name: test_appveyor
  # image: adoptopenjdk/openjdk11:jre-11.0.7_10-alpine
  image: maven:3-jdk-11
  commands:
  - mvn clean verify --batch-mode


- name: graviteebuild
  image: maven:3-jdk-11
  commands:
    - mvn clean compile exec:java -Pdev -pl gravitee-gateway-standalone/gravitee-gateway-standalone-container
