kind: pipeline
# you could have [type: kubernetes]
# type: docker
name: default

environment:
  APIM_VERSION: 6.57.45

- name: dockertest
  image: plugins/docker
  settings:
    repo: hello-world
    tags: latest
    dry_run: true
  environment:
    QUAY_BOT_USERNAME:
      from_secret: quay_bot_username
    QUAY_BOT_SECRET:
      from_secret: quay_bot_secret
  commands:
  - echo "APIM_VERSION=[${APIM_VERSION}]"
  - echo "QUAY_BOT_USERNAME=[${QUAY_BOT_USERNAME}]"
  - echo "QUAY_BOT_SECRET=[${QUAY_BOT_SECRET}]"
  - echo "QUAY_BOT_USERNAME=[$QUAY_BOT_USERNAME]"
  - echo "QUAY_BOT_SECRET=[$QUAY_BOT_SECRET]"
  - docker images && docker ps -a
  secrets: [ quay_bot_username, quay_bot_secret ]

- name: docker_build_n_push
  # image: docker:latest
  image: plugins/docker
  volumes:
    - name: docker_sock
      path: /var/run/docker.sock
  environment:
    QUAY_BOT_USERNAME:
      from_secret: quay_bot_username
    QUAY_BOT_SECRET:
      from_secret: quay_bot_secret
  commands:
  - echo "APIM_VERSION=[${APIM_VERSION}]"
  - echo "QUAY_BOT_USERNAME=[${QUAY_BOT_USERNAME}]"
  - echo "QUAY_BOT_SECRET=[${QUAY_BOT_SECRET}]"
  - echo "QUAY_BOT_USERNAME=[$QUAY_BOT_USERNAME]"
  - echo "QUAY_BOT_SECRET=[$QUAY_BOT_SECRET]"
  - docker images && docker ps -a
  - docker build --no-cache -t "quay.io/gravitee-lab/apim-gateway:$APIM_VERSION" -f docker/Dockerfile docker/
  - docker tag "quay.io/gravitee-lab/apim-gateway:$APIM_VERSION" quay.io/gravitee-lab/apim-gateway:latest
  - docker login -u="$QUAY_BOT_USERNAME" -p="$QUAY_BOT_SECRET" quay.io
  - docker push quay.io/gravitee-lab/apim-gateway:latest
  secrets: [ quay_bot_username, quay_bot_secret ]


# ---
# The java maven build like explained here :
# https://github.com/gravitee-lab/gravitee-gateway/blob/229e4a10dee8c2743b2388560abb6322abc58813/CONTRIBUTING.adoc#submitting-changes
# ---
# This step shoudl fire tests
# ---
- name: contribbuild
  # image: adoptopenjdk/openjdk11:jre-11.0.7_10-alpine
  image: maven:3-jdk-11
  commands:
    - mvn clean install



# ---
# The java maven build defined by the root README.md file :
# https://github.com/gravitee-lab/gravitee-gateway#building
# ---
# - name: graviteebuild
  # image: maven:3-jdk-11
  # commands:
    # - mvn clean compile exec:java -Pdev -pl gravitee-gateway-standalone/gravitee-gateway-standalone-container
