FROM maven:3-jdk-11

# COPY . /gravitee-ci/pipeline/work
RUN mkdir -p /gravitee-ci/pipeline/work
RUN mkdir -p /gravitee-ci/pipeline/tmp/test-results
VOLUME /gravitee-ci/pipeline/work
VOLUME /gravitee-ci/pipeline/tmp/test-results
